api/urls.py
from django.urls import path, include
from rest_framework import routers
from ..api.views import PostViewSet, CategoryViewSet


router = routers.DefaultRouter()
router.register(r'posts', PostViewSet)
router.register(r'category', CategoryViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/',
         include('rest_framework.urls', namespace='rest_framework')),
]

blog/urls.py
from django.shortcuts import redirect
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.conf.urls import url


def posts_page(request):
    return redirect("posts:index")

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("", posts_page),
    path("posts/<id:pk>/", include("posts.urls")),
    path("admin/", admin.site.urls),
    path('api/', include('api.urls')),
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

posts/urls.py
from django.urls import path

from . import views


app_name = "posts"

urlpatterns = [
    path("", views.PostList.as_view(), name="index"),
    path("add/", views.PostCreate.as_view(), name="add"),
    path("<int:pk>", views.PostDetail.as_view(), name="details"),
    path("update/<int:pk>", views.PostUpdate.as_view(), name="update"),
    path("delete/<int:post_id>", views.delete_post, name="delete"),
]

posts/models.py
from django.db import models
from django.urls import reverse
from tags.models import TaggedItem
from django.contrib.contenttypes.fields import GenericRelation


class PostQuerySet(models.QuerySet):
    def published(self):
        return self.filter(status=Post.STATUS_PUBLISHED)


class PostManager(models.Manager):
    def get_queryset(self):
        return PostQuerySet(self.model, using=self._db)

    def published(self):
        return self.get_queryset().published()


class Post(models.Model):
    STATUS_DRAFT = "D"
    STATUS_PUBLISHED = "P"
    STATUS_REJECTED = "R"

    STATUS = (
        (STATUS_DRAFT, "Draft"),
        (STATUS_PUBLISHED, "Published"),
        (STATUS_REJECTED, "Rejected"),
    )

    tags = GenericRelation(TaggedItem)
    objects = PostManager()
    status = models.CharField(
        max_length=100, choices=STATUS, default=STATUS_DRAFT
    )
    title = models.CharField(max_length=100, unique=True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    category = models.ForeignKey(
        "Category",
        on_delete=models.CASCADE,
        null=True,
        default=None,
        related_name="posts",
    )
    categories = models.ManyToManyField("Category", through="PostCategories")

    def get_absolute_url(self):
        return reverse("posts:details", args=[self.pk])

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return self.title

    def get_tags_list(self):
        return [t.tag.name for t in self.tags.all().order_by("-tag__name")]


class Category(models.Model):
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class PostCategories(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="pc")
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="pc"
    )
    is_main = models.BooleanField()

tags/models.py
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=100)


class TaggedItem(models.Model):
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")

posts/forms.py
from django import forms

from .models import Post


def title():
    return forms.CharField(
        label="",
        max_length=100,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "title",
            },
        ),
    )


def content():
    return forms.CharField(
        label="",
        max_length=100,
        widget=forms.Textarea(
            attrs={"class": "form-control", "placeholder": "content"},
        ),
    )


class PostForm(forms.ModelForm):
    title = title()
    content = content()

    class Meta:
        model = Post
        fields = ("title", "content", "status")

api/views.py
from ..posts.models import Post, Category
from api.serializers import CategorySerializer, PostSerializer
from rest_framework import generics, mixins


class PostViewSet(mixins.RetrieveModelMixin,
                  mixins.UpdateModelMixin,
                  mixins.DestroyModelMixin,
                  generics.GenericAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

    def get(self, request, *args, **kwargs):
        return  self.retrieve(request, *args, **kwargs)

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def patch(self, request, *args, ** kwargs):
        return self.partial_update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)


class CategoryViewSet(generics.ListAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

# class PostViewSet(generics.ListAPIView):
#     queryset = Post.objects.all()
#     serializer_class = PostSerializer

posts/views.py
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from .models import Post
from .forms import PostForm


class PostList(ListView):
    model = Post
    template_name = "posts/index.html"
    context_object_name = "posts"

    def get_queryset(self):
        return Post.objects.prefetch_related("pc__category")


class PostDetail(DetailView):
    model = Post
    template_name = "posts/details.html"
    context_object_name = "post"


class PostCreate(CreateView):
    model = Post
    template_name = "posts/add.html"
    form_class = PostForm


class PostUpdate(UpdateView):
    model = Post
    template_name = "posts/update_post.html"
    form_class = PostForm


def delete_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.delete()
    return redirect("posts:index")

tags/views.py
from django.shortcuts import render

# Create your views here.

posts/templates/posts/add.html
{% extends 'posts/base.html' %}

{% block content %}
  <form method="POST">
    {% csrf_token %}
    {{ form.errors }}
    {{ form.as_p }}
    <div class="col-12">
      <button class="btn btn-danger" type="submit">post</button>
    </div><br>
  </form>
{% endblock %}

posts/templates/posts/base.html
<!doctype html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
        crossorigin="anonymous">
</head>
  <body>
    
<div class="container">
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
        <a class="link-secondary" href="#">Subscribe</a>
      </div>
      <div class="col-4 text-center">
        <a class="blog-header-logo text-dark" href="{% url 'posts:index' %}">Home</a>
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        <a class="link-secondary" href="#" aria-label="Search">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
        </a>
        <a class="btn btn-sm btn-outline-secondary" href="#">Sign up</a>
      </div>
    </div>
  </header>

  <div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      <a class="p-2 link-secondary" href="#">World</a>
      <a class="p-2 link-secondary" href="#">U.S.</a>
      <a class="p-2 link-secondary" href="#">Technology</a>
      <a class="p-2 link-secondary" href="#">Design</a>
      <a class="p-2 link-secondary" href="#">Culture</a>
      <a class="p-2 link-secondary" href="#">Business</a>
      <a class="p-2 link-secondary" href="#">Politics</a>
      <a class="p-2 link-secondary" href="#">Opinion</a>
      <a class="p-2 link-secondary" href="#">Science</a>
      <a class="p-2 link-secondary" href="#">Health</a>
      <a class="p-2 link-secondary" href="#">Style</a>
      <a class="p-2 link-secondary" href="#">Travel</a>
    </nav>
  </div>
</div>

<main class="container">
  {% if posts %}
  <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
        <h1 class="display-4 fst-italic">{{ post.title }}</h1>
        <p class="lead my-3">{{ posts.first }}</p>
        <p class="lead mb-0"><a href="{% url 'posts:details' posts.first.id %}" class="text-white fw-bold">details</a></p>
    </div>
  </div>
  {% endif %}


  <div class="row g-5">
    <div class="col-md-8">

        <div class="col-12">
          <a class="btn btn-primary" href="{% url 'posts:add' %}">add post</a>
        </div>
        <hr>

      {% block content %}
      {% endblock %}

    </div>

    <div class="col-md-4">
      <div class="position-sticky" style="top: 2rem;">
        <div class="p-4 mb-3 bg-light rounded">
          <h4 class="fst-italic">About</h4>
          <p class="mb-0">Customize this section to tell your visitors a little bit about your publication, writers, content, or something else entirely. Totally up to you.</p>
        </div>

        <div class="p-4">
          <h4 class="fst-italic">Archives</h4>
          <ol class="list-unstyled mb-0">
            <li><a href="#">March 2021</a></li>
            <li><a href="#">February 2021</a></li>
            <li><a href="#">January 2021</a></li>
            <li><a href="#">December 2020</a></li>
            <li><a href="#">November 2020</a></li>
            <li><a href="#">October 2020</a></li>
            <li><a href="#">September 2020</a></li>
            <li><a href="#">August 2020</a></li>
            <li><a href="#">July 2020</a></li>
            <li><a href="#">June 2020</a></li>
            <li><a href="#">May 2020</a></li>
            <li><a href="#">April 2020</a></li>
          </ol>
        </div>

        <div class="p-4">
          <h4 class="fst-italic">Elsewhere</h4>
          <ol class="list-unstyled">
            <li><a href="#">GitHub</a></li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Facebook</a></li>
          </ol>
        </div>
      </div>
    </div>
  </div>

</main>

<footer class="pt-4 my-md-5 pt-md-5 border-top container">
    <div class="row">
      <div class="col-12 col-md">
        <small class="d-block mb-3 text-muted">© 2017–2021</small>
      </div>
      <div class="col-6 col-md">
        <h5>Features</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Cool stuff</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Random feature</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Resource</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Team</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Locations</a></li>
        </ul>
      </div>
    </div>
  </footer>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
    crossorigin="anonymous">
  </script>
</body>
</html>

posts/templates/posts/details.html
{% extends 'posts/base.html' %}

{% block content %}
  <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">

    <div class="col p-4 d-flex flex-column position-static">
      <strong class="d-inline-block mb-2 text-primary">
        {% for c in post.categories.all %}
            |{{c.name}}
        {% endfor %}
      </strong>

      <h3 class="mb-0">{{ post.title }}</h3>
      <div class="mb-1 text-muted">{{ post.created_at }}</div>
      <p class="card-text mb-auto">{{ post.content }}</p>
      <a class="text-warning" href="{% url 'posts:update' post.id %}">update</a>
      <a class="text-danger" href="{% url 'posts:delete' post.id %}">delete</a>
    </div>

  </div>
{% endblock %}

posts/templates/posts/index.html
{% extends 'posts/base.html' %}


{% block content %}
{% for post in posts %}
  <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
    <div class="col p-4 d-flex flex-column position-static">

      <strong class="d-inline-block mb-2 text-primary">
        {% for c in post.categories.all %}
            |{{c.name}}
        {% endfor %}
      </strong>

      <h3 class="mb-0">{{ post.title }}</h3>
      <div class="mb-1 text-muted">{{ post.created_at }}</div>
      <div class="mb-1 text-muted">{{ post.get_status_display }}</div>
      <p class="card-text mb-auto">{{ post.content }}</p>
      <a href="{% url 'posts:details' post.id%}" class="stretched-link">details</a>
    </div>
  </div>
{% endfor %}
{% endblock %}

posts/templates/posts/update_post.html
{% extends 'posts/base.html' %}

{% block content %}

  <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
    <div class="col p-4 d-flex flex-column position-static">

      <strong class="d-inline-block mb-2 text-primary">
        {% for c in post.categories.all %}
            {{c.name}};
        {% endfor %}
      </strong>

      <h3 class="mb-0">{{ post.title }}</h3>
      <div class="mb-1 text-muted">{{ post.created_at }}</div>
      <p class="card-text mb-auto">{{ post.content }}</p>
      <a class="text-info" href="{% url 'posts:details' post.id %}">back</a>
      <a class="text-danger" href="{% url 'posts:delete' post.id %}">delete</a>
    </div>
  </div>

  <form method="POST">
    {% csrf_token %}
    {{ form.errors }}
    {{ form.as_p }}
    <div class="col-12">
      <button class="btn btn-primary" type="submit">update</button>
    </div><br>
  </form>

{% endblock %}